name: Angular GitHub CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: |
          npm run build

      - name: Save build folder
        uses: actions/upload-artifact@v2
        with:
          name: src
          if-no-files-found: error
          path: src

  ui-chrome-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Download the build folders
        uses: actions/download-artifact@v2
        with:
          name: src
          path: src

      - name: Start Cypress tests
        run: npm run start:ci

      # - name: Cypress run
      #   uses: cypress-io/github-action@v2
      #   with:
      #     install: false
      #     start: yarn start:ci
      #     wait-on: 'http://localhost:4300'
      #     browser: chrome
